language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"

before_install:
  # - "sudo add-apt-repository universe"
  # On older versions of Ubuntu, you might have to use a full source line:
  - "sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe'"

  - "sudo apt-get update"

  - "sudo apt-get install libboost-iostreams"
  # - "sudo apt-get install gearman"
  # - "sudo apt-get install libboost-all-dev"

install:
  - cat /proc/version
  - uname -a
  - cat /etc/issue
  - curl -L https://launchpad.net/gearmand/1.2/1.1.12/+download/gearmand-1.1.12.tar.gz | tar zxv
  - cd gearmand-1.1.12 && ./configure && make && sudo make install

before_script:
  - /usr/local/sbin/gearmand --daemon

notifications:
  email:
    recipients:
      - vaclav.sykora@gmail.com
    on_success: change
    on_failure: change
